### PR TITLE
Bug 4289 demo issues vol3

### LINKED ISSUE #4289: Demo issues vol. 3
Issue gathered are here:
https://docs.google.com/document/d/1vRvnyhejYZ0rkw136PO3Rz1dvB2Syhh9mIw4QZhdDc0/edit#

### PR DESCRIPTION
**Pull request by jjlankinen**
Fixes #4289 

Fixed issues mentioned in google document (https://docs.google.com/document/d/1vRvnyhejYZ0rkw136PO3Rz1dvB2Syhh9mIw4QZhdDc0/edit) except students right to send communicator messages to other students and workspaces and study guiders ability to send messages to their own usergroup members.

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_fi.properties [hunk 1]
```diff
@@ -56,7 +57,7 @@ plugin.images.description.image3 = Otavan Opiston kursseilla kehit
 plugin.images.description.image4 = Koulutuskeskiviikko kokoaa kerran kuussa oppimisesta ja koulutuksesta kiinnostuneet yhteisen teeman ��relle kuulemaan innoittavia alustuksia, jakamaan k�yt�nn�n vinkkej� ja esimerkkej� parhaista toimintatavoista sek� keskustelemaan siit�, miten koulutuskentt�� voidaan k�yt�nn�ss� kehitt��.
 plugin.images.description.image5 = Maahanmuuttajakoulutukset tarjoavat perusopetusta aikuisille. Otavan Opiston kampuksella Savo kohtaa koko maailman.
 
-plugin.frontpage.inactiveStudent.message = <h2>Tervetuloa Muikkuun!</h2><p>N�kym�si on rajoitettu, koska opintosi ovat p��ttyneet. P��set edelleen suoritusrekisteriisi ja tutustumaan kursseihin.</p><p>Ongelmatilanteissa ota yhteytt� Helpdeskiin (<a href="mailto:helpdesk@muikkuverkko.fi">helpdesk@muikkuverkko.fi</a>).</p>
+plugin.frontpage.inactiveStudent.message = <h2>Tervetuloa Muikkuun!</h2><p>N�kym�si on rajoitettu, koska opintosi ovat p��ttyneet. P��set edelleen opinnot n�kym��n ja tutustumaan kursseihin.</p><p>Ongelmatilanteissa ota yhteytt� Helpdeskiin (<a href="mailto:helpdesk@muikkuverkko.fi">helpdesk@muikkuverkko.fi</a>).</p>
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_fi.properties]: opinnot-näkymään

File: muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPagePluginMessages_fi.properties [hunk 2]
```diff
@@ -35,7 +35,7 @@ plugin.images.description.image3 = Otavan Opiston kursseilla kehit
 plugin.images.description.image4 = Koulutuskeskiviikko kokoaa kerran kuussa oppimisesta ja koulutuksesta kiinnostuneet yhteisen teeman ��relle kuulemaan innoittavia alustuksia, jakamaan k�yt�nn�n vinkkej� ja esimerkkej� parhaista toimintatavoista sek� keskustelemaan siit�, miten koulutuskentt�� voidaan k�yt�nn�ss� kehitt��.
 plugin.images.description.image5 = Maahanmuuttajakoulutukset tarjoavat perusopetusta aikuisille. Otavan Opiston kampuksella Savo kohtaa koko maailman.
 
-plugin.frontpage.inactiveStudent.message = <h2>Tervetuloa Muikkuun!</h2><p>N�kym�si on rajoitettu, koska opintosi ovat p��ttyneet. P��set edelleen suoritusrekisteriisi ja tutustumaan kursseihin.</p><p>Ongelmatilanteissa ota yhteytt� Helpdeskiin (<a href="mailto:helpdesk@muikkuverkko.fi">helpdesk@muikkuverkko.fi</a>).</p>
+plugin.frontpage.inactiveStudent.message = <h2>Tervetuloa Muikkuun!</h2><p>N�kym�si on rajoitettu, koska opintosi ovat p��ttyneet. P��set edelleen opinnot n�kym��n ja tutustumaan kursseihin.</p><p>Ongelmatilanteissa ota yhteytt� Helpdeskiin (<a href="mailto:helpdesk@muikkuverkko.fi">helpdesk@muikkuverkko.fi</a>).</p>
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPagePluginMessages_fi.properties]: opinnot-näkymään

File: muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java [hunk 3]
```diff
@@ -321,6 +326,35 @@ private String resolveLoggedUserRoleText() {
   public String getAreaPermissions() {
     return areaPermissions != null ? areaPermissions : "null";
   }
+  
+  public Boolean getUserPropertyAsBoolean(String propertyKey) {
+	String userProperty = this.getUserProperty(propertyKey);
+    if(userProperty != null && "1".equals(userProperty)) {
```
Comment (pkukkon) [inline muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java]: Mixed tabs and spaces. Also
`return userProperty != null && "1".equals(userProperty);`
:P
