### PR TITLE
Bug 1026 slow evaluation

### LINKED ISSUE #1026: Evaluation tool very slow

### PR DESCRIPTION
**Pull request by anttileppa**
Fixes #1026

### CODE REVIEW

File: muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java [hunk 1]
```diff
@@ -1335,8 +1363,8 @@ public Response listWorkspaceAssessments(@PathParam("WORKSPACEENTITYID") Long wo
   }
   
   @GET
-  @Path("/workspaces/{WORKSPACEENTITYID}/users/{ID}")
-  @RESTPermitUnimplemented
+  @Path("/workspaces/{WORKSPACEENTITYID}/students/{ID}")
+  @RESTPermit(handling = Handling.INLINE)
   public Response findWorkspaceUser(@PathParam("WORKSPACEENTITYID") Long workspaceEntityId, @PathParam("ID") String workspaceUserId) {
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java]: workspaceStudentId, findWorkspaceStudent

File: muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java [hunk 2]
```diff
@@ -1412,14 +1454,13 @@ public Response updateWorkspaceUser(@PathParam("WORKSPACEENTITYID") Long workspa
...
-    return Response.ok(workspaceUser).build();
+    return Response.ok(workspaceStudent).build();
   }
 
   @DELETE
-  @Path("/workspaces/{WORKSPACEENTITYID}/users/{ID}")
-  @RESTPermitUnimplemented
+  @Path("/workspaces/{WORKSPACEENTITYID}/students/{ID}")
+  @RESTPermit (handling = Handling.INLINE)
   public Response deleteWorkspaceUser(@PathParam("WORKSPACEENTITYID") Long workspaceEntityId, @PathParam("ID") String workspaceUserId) {
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java]: deleteWorkspaceStudent

File: muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java [hunk 3]
```diff
@@ -1357,16 +1385,30 @@ public Response findWorkspaceUser(@PathParam("WORKSPACEENTITYID") Long workspace
...
+        user.getFirstName(), 
+        user.getLastName(), 
+        user.getStudyProgrammeName(),
+        workspaceUserEntity.getArchived());
+    
+    return Response.ok(workspaceStudent).build();
   }
   
   @PUT
-  @Path("/workspaces/{WORKSPACEENTITYID}/users/{ID}")
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java]: updateWorkspaceStudent

File: muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js [hunk 4]
```diff
@@ -244,29 +244,40 @@
...
-                html: htmlMaterialMap[workspaceEvaluableAssignment.workspaceMaterial.materialId].html,
-                evaluation: evaluation
-              });
-            }, this));
-          }
-          this._loadTemplate(assignments, callback);
+            assignments.push(this._loadAssigmentEvaluation(this.options.workspaceEvaluableAssignments[i], htmlMaterialMap));
+          } 
+          async.parallel(assignments, $.proxy(function(err, results){
+            if(!err){
```
Comment (pkukkon) [inline muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js]: show error

File: muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js [hunk 5]
```diff
@@ -760,34 +736,55 @@
...
-            })
-            .appendTo(this.element.find('.evaluation-students'));
-        }, this));    
+      var studentLoads = $.map(data.workspaceUsers, $.proxy(function (workspaceUser) { 
+        return this._loadStudentAssessments(workspaceUser);
       }, this));
       
-      this._loadAssessmentRequests();
-      this._loadMaterials();
+      async.parallel(studentLoads, $.proxy(function (err, workspaceStudents) {
```
Comment (pkukkon) [inline muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js]: order?

File: muikku-school-data-pyramus/src/main/resources/pyramus-rest-cache-config.json [hunk 6]
```diff
@@ -82,6 +82,36 @@
...
+      "enabledCaches": ["USER", "SYSTEM"],
+      "evictOn": []
+    },
+    "/students/municipalities/{municipalityId}": {
+      "cacheStrategy": "EXPIRES",
+      "expireTime": 300000,
+      "enabledCaches": ["USER", "SYSTEM"],
+      "evictOn": []
+    },
+    "/students/municipalities/{municipalityId}": {
```
Comment (pkukkon) [inline muikku-school-data-pyramus/src/main/resources/pyramus-rest-cache-config.json]: remove duplicate rule
