### PR TITLE
5767 sorter field linebreak fix

### LINKED ISSUE #5767: Rivittyvän vaakasuuntaisen järjestelykentän vastaus ei pysy paikoillaan
Jos vaakasuuntainen järjestelykenttä on niin pitkä, että se rivittyy esim. kahdelle riville, tehtävän vastaus ei näytä pysyvän paikoillaan.

HUOM!
Ongelmat esiintyvät vasta kun raahaamisen sijaan järjestää sanat hiirellä klikkaamalla. Tämä ei myöskään laukaise tehtävän tallennusta tällä hetkellä.

Eli tässä tehtävä on palautettu:
järjestely1
 
Ja tässä selain on päivitetty ja tehtävää menty tarkastelemaan uudelleen. Tehtävä on pysynyt palautettu-tilassa ja muiden kenttien vastaukset ovat pysyneet paikoillaan (muut mahtuvat yhdelle riville).
järjestely2

Lisäksi tehtävään on melko vaikea vastata, jos kenttä rivittyy.

### PR DESCRIPTION
**Pull request by jjlankinen**
Closes #5767

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx [hunk 1]
```diff
@@ -64,7 +64,7 @@ export default class SorterField extends React.Component<SorterFieldProps, Sorte
     if (props.initialValue){
       value = JSON.parse(props.initialValue);
       // We set it up properly
-      items = value.map((v:string)=>this.props.content && this.props.content.items.find(i=>i.id === v));
+      items = value.map((v:string)=>this.props.content && this.props.content.items.find(i=>i.id === v)).filter((v: any) => !!v);
```
Comment (TeroOtavia) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx:67]: This is little bit nitpicking, but this line could use some documentation to explain what happens here and why, not only that "we set it up properly". Especially situation like this when there are `any` typing's that doesn't tell anything about what properties objects holds if they even are objects or something else.

**Review by TeroOtavia — APPROVED** [review]
These are just suggestions.
