### PR TITLE
Bug 872 messages load irregurarly

### LINKED ISSUE #872: Discussion, load more messages button loads one message by time
Long thread, load more button loads only one message.
load_more_messages

### PR DESCRIPTION
**Pull request by avukkonen**
Fixes #872 (maybe)

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 1]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
       element = element.parents(".di-messages-paging");
       var pageElement = $(".di-messages-pages");
       var _this = this;
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: remove _this

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 2]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
...
+        	  renderDustTemplate('/discussion/discussion_page.dust', threads, function(text) {
+                pageElement.append($.parseHTML(text));
             });
-          }
-        });     
+      }
+        }, this));     
       
       }else{
         mApi().forum.areas.threads.read(areaId, {'firstResult' : fRes}).on('$', function(thread, threadCallback) {
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: fres?

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 3]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
...
+        }, this)).callback($.proxy(function(err, threads) {
   
           if (err) {
             $('.notification-queue').notificationQueue('notification', 'error', getLocaleText('plugin.discussion.errormessage.nothreads', err));
           } else {
-
-            renderDustTemplate('/discussion/discussion_page.dust', threads, function(text) {
-              _this._clearLoading(); 
-             pageElement.append($.parseHTML(text));
+            threads.msgLoadCount = threads.length;
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: Duplicate variable

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 4]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
...
       
       }else{
         mApi().forum.areas.threads.read(areaId, {'firstResult' : fRes}).on('$', function(thread, threadCallback) {
 
           mApi().forum.areas.read(thread.forumAreaId).callback(function(err, area) {
             thread.areaName = area.name;
-          });
+
 
           mApi().user.users.basicinfo.read(thread.creator).callback(function(err, user) {
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: indent

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 5]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
...
+            threadCallback();
+          });
           });
-
-          var d = new Date(thread.created);
-    
-          thread.prettyDate = d.toLocaleString();
-    
-          threadCallback();
         }).callback(function(err, threads) {
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: proxy

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 6]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
...
         mApi().forum.areas.threads.read(areaId, {'firstResult' : fRes}).on('$', function(thread, threadCallback) {
 
           mApi().forum.areas.read(thread.forumAreaId).callback(function(err, area) {
             thread.areaName = area.name;
-          });
+
 
           mApi().user.users.basicinfo.read(thread.creator).callback(function(err, user) {
             thread.creatorFullName = user.firstName + ' ' + user.lastName;
+            var d = new Date(thread.created);
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: formatDate

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 7]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
...
+            thread.prettyDate = d.toLocaleString();
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: js should use formatDate and dust template has it's own mechanism for formatting dates

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 8]
```diff
@@ -217,63 +217,56 @@ $(document).ready(function() {
...
-    
-          thread.prettyDate = d.toLocaleString();
-    
-          threadCallback();
         }).callback(function(err, threads) {
           if (err) {
             $('.notification-queue').notificationQueue('notification', 'error', getLocaleText('plugin.discussion.errormessage.nothreads', err));
           }else{
-            _this._clearLoading();
+            thread.msgLoadCount = thread.length;
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: redundant

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 9]
```diff
@@ -302,31 +294,26 @@ $(document).ready(function() {
...
-      mApi().forum.areas.threads.replies.read(areaId, threadId, {'firstResult' : fRes}).on('$', function(replies, repliesCallback) {
+      mApi().forum.areas.threads.replies.read(areaId, threadId, {'firstResult' : fRes}).on('$', $.proxy(function(replies, repliesCallback) {
 
         mApi().forum.areas.read(replies.forumAreaId).callback(function(err, area) {
           replies.areaName = area.name;
 
+          mApi().user.users.basicinfo.read(replies.creator).callback(function(err, user) {
+              replies.creatorFullName = user.firstName + ' ' + user.lastName;
+              var d = new Date(replies.created);
+              replies.prettyDate = d.toLocaleString();
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: formatdate or use dust template date formatting

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 10]
```diff
@@ -335,111 +322,91 @@ $(document).ready(function() {
           replies.pageNo = newPg;
           replies.areaId = areaId;
           replies.threadId = threadId;
+          replies.msgLoadCount = replies.length;
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: redundant

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 11]
```diff
@@ -335,111 +322,91 @@ $(document).ready(function() {
...
-          }
+          mApi().user.users.basicinfo.read(thread.creator).callback(function(err, user) {
+            thread.creatorFullName = user.firstName + ' ' + user.lastName;
+            if(thread.creator == MUIKKU_LOGGED_USER_ID){
+              thread.canEdit = true;
+            }else{
+              thread.canEdit = false;
+            }
+            var d = new Date(thread.created);
+            thread.prettyDate = d.toLocaleString();
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: use formatDate or use dust template formatting
