### PR TITLE
Drag and drop optimization

### LINKED ISSUE #5050: Reordering material pages in desktop Chrome (83) is wonky
When trying to reorder material pages (and sections) by drag and dropping with mouse is nigh on impossible. Sometimes the dragged content seems to disappear completely, sometimes the drag is left on after the mouse button is released, and during the drag the console is flooded with Uncaught (in promise) crashes. Seems to work a lot more consistently in Firefox, for example.

### PR DESCRIPTION
**Pull request by onzag**
Small optimizations to the drag and drop functionality which should allow it to work in a more efficient way and avoid issues with rendering and it being wonky.

Fixes #5050 to a degree, it is still linked to speed.

Also with devtools drag and drop might work differently.

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx [hunk 1]
```diff
@@ -225,7 +225,7 @@ export default class ConnectField extends React.Component<ConnectFieldProps, Con
     this.checkAnswers();
   }
   //swapping the fields
-  swapField(fielda: FieldType, fieldb: FieldType){
+  swapField(triggerChange: boolean, fielda: FieldType, fieldb: FieldType){
```
Comment (avukkonen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx:228]: fieldA, fieldB?

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx [hunk 2]
```diff
@@ -271,6 +281,11 @@ export default class Draggable extends React.Component<DraggableProps, Draggable
     }
   }
   onRootSeletEnd(e: MouseEvent | TouchEvent){
```
Comment (avukkonen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx:283]: onRootSelectEnd?

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx [hunk 3]
```diff
@@ -241,10 +241,10 @@ export default class ConnectField extends React.Component<ConnectFieldProps, Con
         }
         return f;
       })
-    }, this.triggerChange)
+    }, triggerChange ? this.triggerChange : null)
   }
   //swapping two counterparts, same as fields
-  swapCounterpart(fielda: FieldType, fieldb: FieldType){
+  swapCounterpart(triggerChange: boolean, fielda: FieldType, fieldb: FieldType){
```
Comment (TeroOtavia) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx:247]: Shorter way to express this is could be:
```
triggerChange && this.triggerChange
```

**Review by avukkonen — CHANGES_REQUESTED** [review]

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx (hunk 3 above)
Comment (onzag) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx:247]: I don't understand, it's a parameter; why would it be part of "this"?

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx (hunk 1 above)
Comment (onzag) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx:228]: Yes that's what they mean, it would be nicer to name them fieldA and fieldB in camel case but they were originall named like that, I'd have to otherwise rename everywhere they were used.

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx (hunk 2 above)
Comment (onzag) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx:283]: Haven't changed that line but the element to drag is called the root in that component, the function triggers on mouse event and touch event; so it's a select event, so the function ended up named on root select end, referring to both mouseend and touchend.

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx [hunk 4]
```diff
@@ -257,12 +257,12 @@ export default class ConnectField extends React.Component<ConnectFieldProps, Con
         }
         return f;
       })
-    }, this.triggerChange)
+    }, triggerChange ? this.triggerChange : null)
```
Comment (TeroOtavia) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx:260]: Shorter way to express this is could be:
```
triggerChange && this.triggerChange
```

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx (hunk 2 above)
Comment (DerangedPineapple) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx:283]: **onRootSeletEnd** is not the same as suggested **onRootSelectEnd**. Find the typo. Might be better to point the typo in the future if that was the case here.

Comment (jjlankinen) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx:283]: onRootSeletEnd is not the same as suggested onRootSelectEnd. Find the typo. Might be better to point the typo in the future if that was the case here.

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx (hunk 1 above)
Comment (avukkonen) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx:228]: I don't see the problem in it, but fair enough. Not a big issue.

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx (hunk 4 above)
Comment (jjlankinen) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx:260]: At least the naming of the variable should be different from the function so it would be easier to read in future.

**Review by avukkonen — APPROVED** [review]
