### PR TITLE
Ftr 1116 reply to failed

### LINKED ISSUE #1116: Allow students reply exercises if grade is non passing

### PR DESCRIPTION
**Pull request by hkurhinen**
fixes #1116

### CODE REVIEW

File: muikku-evaluation-plugin/src/main/java/fi/muikku/plugins/evaluation/EvaluationController.java [hunk 1]
```diff
@@ -62,12 +62,13 @@ public WorkspaceMaterialEvaluation createOrUpdateWorkspaceMaterialEvaluation(Use
           evaluated, 
           verbalAssessment);
     }
-
+    //grade.is
```
Comment (anttileppa) [inline muikku-evaluation-plugin/src/main/java/fi/muikku/plugins/evaluation/EvaluationController.java]: remove this
