### PR TITLE
Workspace material sort fix

### LINKED ISSUE #2687: Assignment's wrong order in evaluation
Assignments are listed sometimes in wrong order in evaluation. Workspace LI1 (https://otavanopisto.muikkuverkko.fi/evaluation?workspaceEntityId=3045) shows 6.9, 1.1 and 4.4 in wrong place.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1343

#### SH
Jari Sarja

### PR DESCRIPTION
**Pull request by pkukkon**
- fixes #2687

### CODE REVIEW

File: muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java [hunk 1]
```diff
@@ -743,24 +743,16 @@ public Long getMaterialCountByWorkspaceAndAssignmentType(WorkspaceEntity workspa
...
     List<WorkspaceMaterial> workspaceMaterials = workspaceMaterialDAO.listByHiddenAndAssignmentTypeAndParents(Boolean.FALSE, assignmentType, folders);
-
     Collections.sort(workspaceMaterials, new Comparator<WorkspaceMaterial>() {
-      
       @Override
       public int compare(WorkspaceMaterial o1, WorkspaceMaterial o2) {
-        int result = getParentIndex(o1.getParent()) - getParentIndex(o2.getParent());
+        int result = o1.getParent().getOrderNumber() - o2.getParent().getOrderNumber();
         if (result == 0) {
           result = o1.getOrderNumber().compareTo(o2.getOrderNumber());
```
Comment (anttiviljakainen) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java]: This is probably redundant, compareTo does the same (kind of) comparison between the ordernumbers. Afaik the magnitude doesn't matter, only the -1/0/1 output. So maybe just 
o1.getOrderNumber().compareTo(o2.getOrderNumber()); for simplicity?

Comment (anttiviljakainen) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java]: Should've said -/0/+.

Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java]: Yes, magnitude does not matter but since the two materials aren't necessarily under the same folder, the first comparison has to be made on their folders. Don't really see any way to make this simpler.

Comment (anttiviljakainen) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java]: Bah I failed to notice the difference. Good job.
