### PR TITLE
Fixes #468 student records not working

### LINKED ISSUE #468: (student) records not working
Student gets code and link that is not working.
records

### PR DESCRIPTION
**Pull request by avukkonen**
By taking the description from data-attribute to hidden div container

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js [hunk 1]
```diff
@@ -104,10 +104,10 @@
     },
     _onItemClick: function (event) {
       var item = $(event.target).hasClass('tr-item') ? $(event.target) : $(event.target).closest('.tr-item');
-
+      
       var workspaceEntityId = $(item).attr('data-workspace-entity-id');
       var workspaceEntityName =  $(item).attr('data-workspace-entity-name');
-      var workspaceEntityDescription = $(item).attr('data-workspace-entity-description');
+      var workspaceEntityDescription = $(item).find('#description').html();
```
Comment (anttileppa) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js]: .html() vs text() ?
