### PR TITLE
fixes the external view link

### LINKED ISSUE #7127: Työtilan asetukset: Näytä työtila Pyramuksessa
Jos kurssin asetuksissa klikkaa **Näytä kurssi Pyramuksessa** niin ei tapahdu mitään (mikään ei devikonsolin mukaan edes kaadu). Pitäisi avata kurssi Pyramuksessa uuteen välilehteen. Kyseinen linkki tulee frontille additionalInfo-endpointin viewLink-kentän arvona, joten ilmeisesti jonkin sortin käyttisfiba?

### LINKED ISSUE #7128: Kurssin chat-asetus ei tallennu
Kurssin eli työtilan chat-huone käytössä -asetusten valintoja on tyhjentynyt eikä uutta asetusta voi tehdä.

### PR DESCRIPTION
**Pull request by avukkonen**
fixes #7127 
fixes #7128

### CODE REVIEW

**Review by TeroOtavia — APPROVED** [review]

File: muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSettingsRestModel.java [hunk 1]
```diff
@@ -235,14 +238,23 @@ public boolean isChatEnabled() {
   public void setChatEnabled(boolean chatEnabled) {
     this.chatEnabled = chatEnabled;
   }
+  
+  public String getExternalViewLink()  {
+	  return externalViewLink;
+  }
 
+  public void setExternalViewLink(String externalViewLink)  {
+	  this.externalViewLink = externalViewLink;
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSettingsRestModel.java:247]: Remove tab from indentation (same with the getter)

**Review by pkukkon — CHANGES_REQUESTED** [review]

**Review by pkukkon — APPROVED** [review]
Backend OK
