### PR TITLE
Fixed issue with some roles not seeing workspaces in announcer

### LINKED ISSUE #2891: Workspace announcement is marked as environment announcement in workspace announcer for people who are not workspace staff members
#### Details

 - Workspace announcements are marked as an environment announcement erroneously, and if you edit them, they're published as environment announcements
 - When showing workspace announcements in environment front page, show one workspace that it's published in, and a number that shows how many other workspaces it's published in

#### Example

This announcement has been published to the workspace and then being edited.

screen shot 2017-01-27 at 14 02 26

Link: https://otavanopisto.muikkuverkko.fi/workspace/kesaopiskelun-7-ottelu/announcer

### PR DESCRIPTION
**Pull request by anttiviljakainen**
Closes #2891

### CODE REVIEW

File: muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java [hunk 1]
```diff
@@ -1,14 +1,15 @@
 package fi.otavanopisto.muikku.plugins.announcer;
 
+import java.util.ArrayList;
 import java.util.Collections;
 import java.util.Comparator;
 import java.util.Date;
 import java.util.List;
-import java.util.ArrayList;
+import java.util.Set;
+import java.util.stream.Collectors;
```
Comment (anttiviljakainen) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java]: Yes, line 155.
