### PR TITLE
Bug 1660 data transfer prohibition

### LINKED ISSUE #1660: User with "data transfer prohibition" cannot be seen in guider or in ToR
Annukka Manninen reported that a student cannot be seen in guider. There are also other problems considering (at least) ToR - posibly more.

The student has a prohibiton for submitting his/her information forward, so I cannot quote the original report here.

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=417

### PR DESCRIPTION
**Pull request by anttileppa**
Fixes #1660

### CODE REVIEW

File: muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java [hunk 1]
```diff
@@ -209,6 +210,18 @@ public Response searchStudents(
       }
     } 
     
+    if (Boolean.TRUE.equals(includeHidden)) {
+      if (!sessionController.hasEnvironmentPermission(MuikkuPermissions.LIST_HIDDEN_STUDENTS)) {
+        if (userEntityId == null) {
+          return Response.status(Status.FORBIDDEN).build();
```
Comment (ilmoeuro) [inline muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java]: Some kind of message in entity() would save a lot of debugging time in the future
