### PR TITLE
Removed questionable stateless annotations

### LINKED ISSUE #2016: Workspace material replies can cause Muikku crashes
Related to WorkspaceMaterialReplyController being stateless?

### PR DESCRIPTION
**Pull request by pkukkon**
- fixes #2016 (?)

### CODE REVIEW

File: muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialDeleteListener.java [hunk 1]
```diff
@@ -11,7 +10,6 @@
 import fi.otavanopisto.muikku.plugins.workspace.model.WorkspaceMaterialField;
 import fi.otavanopisto.muikku.plugins.workspace.model.WorkspaceMaterialReply;
 
-@Stateless
 public class WorkspaceMaterialDeleteListener {
```
Comment (petja-laitila) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialDeleteListener.java]: ApplicationScope
