### PR TITLE
** Fixed issue #1399

### LINKED ISSUE #1399: Locales when browser language is "other"
When browser language is something else than Finnish or English, the environment does not recognize it and becomes confusing. 

"Other" should always be Finnish or English.

Stakeholder: Jaana Matkaselkä
osTikcket: 359717

### PR DESCRIPTION
**Pull request by anttileppa**
Fixes #1399

### CODE REVIEW

File: muikku-core/src/main/java/fi/muikku/session/local/LocalSessionControllerImpl.java [hunk 1]
```diff
@@ -31,6 +32,7 @@
 public class LocalSessionControllerImpl extends AbstractSessionController implements Serializable, LocalSessionController {
   
   private static final long serialVersionUID = 4947154641883149837L;
+  private static final String[] SUPPORTED_LOCALES = {"fi", "en"};
```
Comment (hkurhinen) [inline muikku-core/src/main/java/fi/muikku/session/local/LocalSessionControllerImpl.java]: Maybe in future this should be made configurable but this is ok for now.
