### PR TITLE
Workspace staff member synchronization bug fixes

### LINKED ISSUE #3806: Workspace staff member role does not update properly
If a staff member is (or has been) in any workspace in any role, changes to that role in Pyramus are not reflected in Muikku.

### PR DESCRIPTION
**Pull request by pkukkon**
- fixes #3806 (Muikku didn't react to an existing workspace staff member getting a new role in Pyramus)
- scheduled background synchronization of course staff members now archives those workspace staff members that were removed in Pyramus but Muikku somehow failed to process the related event

### CODE REVIEW

File: muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java [hunk 1]
```diff
@@ -515,8 +534,32 @@ public int updateCourseStaffMembers(Long courseId) {
...
     }
+    
+    // At this point current staff members only contain those that Pyramus no longer acknowledges.
+    // We have somehow missed their original removal event but fake them here to get staff in sync.
+    
+    for (WorkspaceUserEntity currentStaffMember : currentStaffMembers) {
+      try {
+        String courseStaffMemberIdentifier = currentStaffMember.getIdentifier();
+        String staffMemberIdentifier = currentStaffMember.getUserSchoolDataIdentifier().getUserEntity().getDefaultIdentifier();
+        Long courseStaffMemberId = NumberUtils.toLong(StringUtils.substringAfterLast(courseStaffMemberIdentifier, "-"));
```
Comment (anttiviljakainen) [inline muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java]: Use PyramusIdentifierMapper instead of explicit Long conversion (getPyramusCourseStaffId and getPyramusStaffId below [check])
