### PR TITLE
Fixed browser navigation in discussion

### LINKED ISSUE #3136: Fix browser back button in discussion

### PR DESCRIPTION
**Pull request by anttiviljakainen**
Fixes #3136

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js [hunk 1]
```diff
@@ -144,13 +144,31 @@
...
 
+      $(window).on("hashchange", $.proxy(function () {
+        if (this._currentLocation != window.location.hash) {
+          var location = this._parseHash();
+          this._allAreas = location.allAreas;
+
+          if (location.areaId && location.threadId) {
+            this.loadThread(location.areaId, location.threadId);
+          } else {
+            if (!location.areaId || this._allAreas) {
```
Comment (anttiviljakainen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: Care to elaborate sir?

Comment (pkukkon) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js]: Probably the space after function on line 155?
