### PR TITLE
Calendar timezone

### LINKED ISSUE #191: Wrong times in calendar
When I add a new calendar entry or move it in Google Calendar, the time of the event is one or two hours off.

### PR DESCRIPTION
**Pull request by avukkonen**
Fixes #191
Fixes Datepicker bug in chrome

### CODE REVIEW

File: muikku-calendar/src/main/resources/META-INF/resources/scripts/gui/calendar.js [hunk 1]
```diff
@@ -65,8 +65,8 @@
          values.start = eventStart;
          values.end = eventStop;
          values.status = 'CONFIRMED';
-         values.startTimeZone = 'GMT+3';
-         values.endTimeZone = 'GMT+3';        
+         values.startTimeZone = 'GMT+2';
+         values.endTimeZone = 'GMT+2';
```
Comment (anttiviljakainen) [inline muikku-calendar/src/main/resources/META-INF/resources/scripts/gui/calendar.js]: These should most likely be "localized" too as this change i believe is based on daylight savings. More concretely, this setting should come from the users' current timezone.
