### PR TITLE
Fix for missing (and eventually NaN) submit dates in evaluation

### LINKED ISSUE #2611: Problem in task evaluation - answer date is NaN.NaN.NaN, aN:aN
Mia Siven:

andersin_ella

## Osticket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1288

### PR DESCRIPTION
**Pull request by pkukkon**
- fixes #2611

### CODE REVIEW

File: muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js [hunk 1]
```diff
@@ -708,7 +708,7 @@
           assessors: this.options.assessors,
           workspaceName: this.options.workspaceName,
           studentStudyProgrammeName: this.options.studentStudyProgrammeName,
-          submitDate: new Date(moment(this.options.submitDate)),
+          submitDate: this.options.submitDate ? new Date(moment(this.options.submitDate)) : null,
```
Comment (ilmoeuro) [inline muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js]: use moment(...).toDate()

Comment (pkukkon) [inline muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js]: Let's fix these collectively in #2630
