### PR TITLE
Changes:

### LINKED ISSUE #5774: Evaluation crash to some bugs
Bug fixes for evaluation

### PR DESCRIPTION
**Pull request by TeroOtavia**
- bug fixes, manager won't get evaluation crashed when going around workspace to evaluation
- bug fixes, when admin tries to change assignment evaluation to supplementation

resolves #5774

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx [hunk 1]
```diff
@@ -24,12 +24,15 @@ import {
 } from "~/actions/main-function/evaluation/evaluationActions";
 import "~/sass/elements/assignment.scss";
 import "~/sass/elements/empty.scss";
+import { WorkspaceType } from "../../../../../reducers/workspaces/index";
```
Comment (jjlankinen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx]: Use tilde instead of relative path as tilde automatically starts from app root.

**Review by jjlankinen — CHANGES_REQUESTED** [review]

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx (hunk 1 above)
Comment (TeroOtavia) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx]: Fixed in previous commit

**Review by jjlankinen — DISMISSED** [review]

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx [hunk 2]
```diff
@@ -286,6 +289,24 @@ export class Evaluation extends React.Component<
...
+    const workspaces = [...this.props.evaluation.evaluationWorkspaces];
+
+    /**
+     * This is because, when admin goes to workspace where he/she is not
+     * workspace teacher, the select list will be missing that current active workspace.
+     * So here we check if its not in the list and push currentWorkspace as temporary option
+     */
+    if (
+      this.props.currentWorkspace &&
+      this.props.evaluation.evaluationWorkspaces
```
Comment (avukkonen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx:304]: Could .some() be used here instead of .map()?

**Review by avukkonen — CHANGES_REQUESTED** [review]

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx [hunk 3]
```diff
@@ -286,6 +292,24 @@ export class Evaluation extends React.Component<
...
+        .map((eWorkspace) => eWorkspace.id)
```
Comment (avukkonen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx:305]: You could use some instead

**Review by avukkonen — CHANGES_REQUESTED** [review]

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx (hunk 3 above)
Comment (TeroOtavia) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx]: Fixed

**Review by avukkonen — APPROVED** [review]
