### PR TITLE
Bug 3345 discussion test fix

### LINKED ISSUE #3345: Discussion test fixing

### PR DESCRIPTION
**Pull request by petja-laitila**
Fixes #3345 and also updates wiremock

### CODE REVIEW

File: muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java [hunk 1]
```diff
@@ -294,7 +293,7 @@ protected RemoteWebDriver createSauceWebDriver() throws MalformedURLException {
     capabilities.setCapability("timeZone", "Universal");
     capabilities.setCapability("seleniumVersion", seleniumVersion);
     
-    if (!StringUtils.isBlank(browserResolution)) {
+    if (!org.apache.commons.lang3.StringUtils.isBlank(browserResolution)) {
```
Comment (ilmoeuro) [inline muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java]: Add import for `StringUtils`

File: muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java [hunk 2]
```diff
@@ -947,7 +946,7 @@ public Builder wiremockReset() {
       public Builder dumpMocks() {
         System.out.print("dumpMocks");
         
-        ListStubMappingsResult listAllStubMappings = WireMock.listAllStubMappings();
+        com.github.tomakehurst.wiremock.admin.model.ListStubMappingsResult listAllStubMappings = WireMock.listAllStubMappings();
```
Comment (ilmoeuro) [inline muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java]: Add import for `ListStubMappingsResult`

Comment (petja-laitila) [inline muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java]: Done
