### PR TITLE
* Fixed workspace guides toc__header layout

### LINKED ISSUE #6499: Kurssin ohjeet: sisällysluettelo
Kurssin ohjeiden sisällysluettelo on vaihtanut oudosti paikkaa, ks. kuva:
image

### PR DESCRIPTION
**Pull request by jjlankinen**
Closes #6499

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/content.tsx [hunk 1]
```diff
@@ -415,6 +415,7 @@ class ContentComponent extends React.Component<ContentProps, ContentState> {
 
     return (
       <Toc
+        modifier="workspace-guides"
```
Comment (avukkonen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/content.tsx:418]: in the locales I call these "insttructions" (ohjeet?)

**Review by avukkonen — CHANGES_REQUESTED** [review]

**Review by avukkonen — APPROVED** [review]
