### PR TITLE
4900 organization workspace list load more workspaces func

### LINKED ISSUE #4900: Organization workspace list - load more workspaces functionality
This needs to be checked and it's not likely to work. Needs to be working, then. Duh.

### LINKED ISSUE #4901: Organization workspaces - Filters do not work on refresh
Found a bug where existing filters do not work on refresh or entry.

### PR DESCRIPTION
**Pull request by avukkonen**
closes #4900 
closes #4901

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/locales.ts [hunk 1]
```diff
@@ -4,15 +4,15 @@ import $ from '~/lib/jquery';
...
+  AVAILABLE: {
     name: string,
     locale: string
   }[],
   current: string
 }
 
 export default function locales(state={
-  avaliable: $.makeArray($("#language-picker a").map((index: number, element: HTMLElement)=>{
+  AVAILABLE: $.makeArray($("#language-picker a").map((index: number, element: HTMLElement)=>{
```
Comment (onzag) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/locales.ts]: Why was it renamed into uppercase?...

Comment (avukkonen) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/locales.ts]: Must be a mistake.

Comment (avukkonen) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/locales.ts]: Aha yes, I replaced a bunch of typo stuff: "avaliable" is a typo.

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navbar/language-picker.tsx [hunk 2]
```diff
@@ -22,7 +22,7 @@ interface LanguagePickerState {
 
 class LanguagePicker extends React.Component<LanguagePickerProps, LanguagePickerState> {
   render(){
-    return <Dropdown modifier="language-picker" items={this.props.locales.avaliable.map((locale)=>{
+    return <Dropdown modifier="language-picker" items={this.props.locales.AVAILABLE.map((locale)=>{
```
Comment (onzag) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navbar/language-picker.tsx]: This would have caused a crash, now it is lowercase in one place and uppercase in the reducer.
