### PR TITLE
Synchronized REST access token handling

### LINKED ISSUE #2468: Token concurrency issues with batch REST calls
When making batch calls to Pyramus, Muikku fails to handle access token refreshing in a graceful manner.

### PR DESCRIPTION
**Pull request by pkukkon**
- fixes #2468

### CODE REVIEW

File: muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/UserPyramusClient.java [hunk 1]
```diff
@@ -110,29 +110,26 @@ public void delete(String path) {
     }
   }
```
Comment (ilmoeuro) [inline muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/UserPyramusClient.java]: Remove @Lock from class

File: muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/SystemAccessTokenProvider.java [hunk 2]
```diff
@@ -39,20 +38,17 @@ public void init() {
     }
```
Comment (ilmoeuro) [inline muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/SystemAccessTokenProvider.java]: Remove @Singleton

Comment (pkukkon) [inline muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/SystemAccessTokenProvider.java]: Opted to not to add synchronized after all, as @Singleton provides concurrency in a much better fashion
