### PR TITLE
Bug 1001 hide answers button

### LINKED ISSUE #1001: Workspace exercises hide/show correct answers button
Exercises "Hide correct answers" button doesn't change to back "Show correct answers" when user updates his answer and wan't to recheck it. Exercise's examples per field does hide correctly.

### PR DESCRIPTION
**Pull request by jjlankinen**
Fixes #1001

### CODE REVIEW

File: muikku/src/main/webapp/resources/scripts/gui/muikku-field.js [hunk 1]
```diff
@@ -599,9 +595,19 @@
       this._saveFailedTimeoutId = null;
 
       $(document).connectionLostNotifier("notifyReconnected");
+      
+//      var page = $(this.element).closest('.workspace-materials-view-page');
```
Comment (anttileppa) [inline muikku/src/main/webapp/resources/scripts/gui/muikku-field.js]: Remove these lines
