### PR TITLE
Bug 1893 coursepicker paging

### LINKED ISSUE #1893: Course picker paging is replacing course list instead of adding more to the list

### PR DESCRIPTION
**Pull request by avukkonen**
Fixes #1893

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js [hunk 1]
```diff
@@ -160,9 +165,10 @@
       window.location = CONTEXTPATH + '/workspace/' + workspaceUrl;
     }, 
     
-    _loadMore: function () {
+    _loadMore: function () {        
       this._firstResult += this._maxResults;
-      this._loadWorkspaces();
+      hasPage = true;
+      this._loadWorkspaces(hasPage);
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js]: Variable hasPage isn't really needed here; this._loadWorkspaces(true); would be sufficient. Alternatively, local variables should be declared as such (var hasPage = true)
