### PR TITLE
Various fixes for study time end notification

### LINKED ISSUE #2878: Study time end notifications are sent to students whose study time is already over

### PR DESCRIPTION
**Pull request by pkukkon**
- fixes #2878

### CODE REVIEW

File: muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java [hunk 1]
```diff
@@ -166,8 +168,9 @@ public SearchResult searchUsers(String text, String[] textFields, Collection<Env
       if (startedStudiesBefore != null ) {
         query.must(rangeQuery("studyStartDate").lt((long) startedStudiesBefore.getTime() / 1000));
       }
-      
-      if(studyTimeEndsBefore != null) {
+
+      if (studyTimeEndsBefore != null) {
+        query.must(rangeQuery("studyTimeEnd").gte(now));
```
Comment (anttiviljakainen) [inline muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java]: Is this gte necessary?

Comment (anttiviljakainen) [inline muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java]: Ok I guess it is in use in the notifier but the function declaration isn't necessarily explicit about the functionality (I would guess it returns all that have the studytimeend < specified regardless of current date).

File: muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/StudyTimeNotificationStrategy.java [hunk 2]
```diff
@@ -102,10 +103,19 @@ public void sendNotifications() {
...
         
+        // Do not notify students that have no study start date set or have started their studies within the last 60 days
+        
         if (student.getStudyStartDate() == null || student.getStudyStartDate().isAfter(sendNotificationIfStudentStartedBefore)) {
           continue;
         }
         
+        // Double check that the study time really is ending in 60 days
+        
+        if (student.getStudyTimeEnd() == null || student.getStudyTimeEnd().isAfter(studyTimeEndsOdt) || student.getStudyTimeEnd().isBefore(OffsetDateTime.now())) {
```
Comment (anttiviljakainen) [inline muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/StudyTimeNotificationStrategy.java]: I guess all returned students have studytimeend specified as this would scream a bunch if it wasn't.
