### PR TITLE
404 error from loading avatar is fixed:

### LINKED ISSUE #3845: Don't attempt to load non-existing profile pictures
Discussion areas with lots of messages spams the profile picture url for all senders even if they dont exist. Preload this information from server and avoid doing 404 calls.

### PR DESCRIPTION
**Pull request by TeroOtavia**
- Avatar component is use everywhere where avatar is needed
- contains some minor changes and code cleaning
    - current-thread.tsx
    - discussion-threads.tsx
    - threads.tsx
    - avatar.tsx
    - summary.tsx

Resolves #3845

### CODE REVIEW

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx [hunk 1]
```diff
@@ -1,20 +1,56 @@
...
-  return props.hasImage ? <object className="avatar-container"
-    data={getUserImageUrl(props.id)}
-    type="image/jpeg">
-     <div className={`avatar avatar--category-${userCategory}`}>{props.firstName[0]}</div>
-  </object> : <div className="avatar-container">
-     <div className={`avatar avatar--category-${userCategory}`}>{props.firstName[0]}</div>
-  </div>
+interface AvatarState {}
+
+class Avatar extends React.Component<AvatarProps, AvatarState> {
```
Comment (avukkonen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx:19]: This is still a stateless component so it should remain a function?

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx [hunk 2]
```diff
@@ -1,20 +1,56 @@
...
 
 interface AvatarProps {
-  hasImage: boolean,
-  id: number,
-  firstName: string
+  hasImage: boolean;
+  id: number;
+  firstName: string;
+  userCategory?: number;
+  i18n: i18nType;
```
Comment (avukkonen) [inline muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx:13]: Why does it need i18n? It's not used anywhere.

**Review by avukkonen — CHANGES_REQUESTED** [review]

File: muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx (hunk 1 above)
Comment (TeroOtavia) [reply muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx]: Removed. Left overs when I tried get i18n locales from redux, but it wasn't necessary.
