### PR TITLE
Fixes #3832 xmpp prebind fails

### LINKED ISSUE #3832: Xmpp prebind fails when session closes before converse can reattach to it

### PR DESCRIPTION
**Pull request by saaralepisto**
Fixes #3832 xmpp prebind fails

### CODE REVIEW

File: muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatClientHolder.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+import javax.ejb.ConcurrencyManagement;
+import javax.ejb.ConcurrencyManagementType;
+import javax.ejb.Schedule;
+import javax.ejb.Singleton;
+import javax.inject.Inject;
+
+import rocks.xmpp.core.session.XmppClient;
+
+@Singleton
+@ConcurrencyManagement(ConcurrencyManagementType.BEAN)
```
Comment (anttiviljakainen) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatClientHolder.java]: Is this necessary, iirc the default is write lock anyways so no public method can be called at the same time.

File: muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatUserSyncScheduler.java [hunk 2]
```diff
@@ -1,112 +1,112 @@
...
-          userEntity = new UserEntity(enabledUser, user.getDisplayName(), "", password);
-          client.createUser(userEntity);
-        }
-      } catch (Exception e) {
-        logger.log(Level.INFO, "Exception when syncing user " + enabledUser, e);
-      }
-    }
-  }
-}
+package fi.otavanopisto.muikku.plugins.chat;
```
Comment (anttiviljakainen) [inline muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatUserSyncScheduler.java]: Are there some linebreak etc changes that show the whole file as changed?
