### PR TITLE
Bug 1050 evaluation userentityids

### LINKED ISSUE #1050: Evaluation view users userEntityId
Evaluation view users userEntityId instead of workspaceStudentId

### PR DESCRIPTION
**Pull request by anttileppa**
Fixes #1050

### CODE REVIEW

File: muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java [hunk 1]
```diff
@@ -196,20 +140,44 @@ public Response deleteAssessmentRequest(
       return Response.status(Status.UNAUTHORIZED).build();
     }
     
+    SchoolDataIdentifier assessmentRequestIdentifier = SchoolDataIdentifier.fromId(assessmentRequestId);
+    if (assessmentRequestId == null) {
+      return Response.status(Status.BAD_REQUEST).entity("Invalid assessmentRequestIdentifier").build();
+    }
+    
     WorkspaceEntity workspaceEntity = workspaceController.findWorkspaceEntityById(workspaceEntityId);
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java]: Add null checks

File: muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java [hunk 2]
```diff
@@ -196,20 +140,44 @@ public Response deleteAssessmentRequest(
...
     WorkspaceUserEntity workspaceUserEntity = workspaceUserEntityController.findWorkspaceUserByWorkspaceEntityAndUserIdentifier(workspaceEntity, sessionController.getLoggedUser());    
-    assessmentRequestController.deleteWorkspaceAssessmentRequest(workspaceUserEntity, assessmentRequestId);
     
-    communicatorAssessmentRequestController.sendAssessmentRequestCancelledMessage(workspaceUserEntity);
+    SchoolDataIdentifier workspaceIdentifier = new SchoolDataIdentifier(workspaceEntity.getIdentifier(), workspaceEntity.getDataSource().getIdentifier());
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java]: Check that logged user and studentIdentifier matches
