### PR TITLE
Plenty of bug fixes to searching and archiving workspace users

### LINKED ISSUE #1012: School data source event unarchives an archived workspace student
When a student is archived from a workspace, it leads to an event of Pyramus student having been updated, which in turn unarchives the freshly archived student.

### PR DESCRIPTION
**Pull request by pkukkon**
- fixes #1012

### CODE REVIEW

File: muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java [hunk 1]
```diff
@@ -1349,11 +1349,11 @@ public Response findWorkspaceUser(@PathParam("WORKSPACEENTITYID") Long workspace
...
       return Response.status(Status.FORBIDDEN).build();
     }
-    SchoolDataIdentifier userIdentifier = SchoolDataIdentifier.fromId(userId);
-    if (userIdentifier == null) {
+    SchoolDataIdentifier workspaceUserIdentifier = SchoolDataIdentifier.fromId(workspaceUserId);
+    if (workspaceUserIdentifier == null) {
       return Response.status(Status.BAD_REQUEST).entity("Invalid workspace user id").build();
     }
-    fi.muikku.schooldata.entity.WorkspaceUser bridgeUser = workspaceController.findWorkspaceUser(workspaceIdentifier, userIdentifier);
+    fi.muikku.schooldata.entity.WorkspaceUser bridgeUser = workspaceController.findWorkspaceUser(workspaceIdentifier, workspaceUserIdentifier);
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java]: userIdentifier!

File: muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java [hunk 2]
```diff
@@ -1399,16 +1399,15 @@ public Response updateWorkspaceUser(@PathParam("WORKSPACEENTITYID") Long workspa
...
       }
       else {
         // Unarchive
-        WorkspaceUserEntity workspaceUserEntity = workspaceUserEntityController.findWorkspaceUserEntityByWorkspaceAndIdentifierAndArchived(
-            workspaceEntity, workspaceUserIdentifier.getIdentifier(), Boolean.TRUE);
+        WorkspaceUserEntity workspaceUserEntity = workspaceUserEntityController.findWorkspaceUserEntityByWorkspaceUserIdentifierAndArchived(
+            workspaceUserIdentifier, Boolean.TRUE);
         if (workspaceUserEntity != null) {
           workspaceUserEntityController.unarchiveWorkspaceUserEntity(workspaceUserEntity);
         }
```
Comment (pkukkon) [inline muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java]: if user does not yet exist it should be added
